### PR TITLE
Fix #429

### LINKED ISSUE #429: Shimmering Sand Turns Into Snow Layer
### Describe the Bug

When middle clicking a shimmering sand game gives snow layer. Shimmering sands also turn into snow layers when falling

### Reproduction Steps

1.Put shimmering sand, middle click with the mouse
2.Put shimmering sand, break the block underneath it and make it fall

### Expected Result

Expected not to see a snow layer. I think it is very obvius

### Screenshots and Videos

_No response_

### Operating System

Windows 10

### Mod Version

2.5.3

### Minecraft Version

1.19.2

### Forge Version

43.2.8

### Other Mods

[modlist.txt](https://github.com/infernalstudios/Infernal-Expansion/files/11362174/modlist.txt)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SwanX1**
Snow! Real Magic uses a mixin into SnowLayerBlock, which causes the issue, a simple fix by reimplementing SnowLayerBlock instead of extending it was made. Snow! Real Magic no longer mixins into the class. (Tested using commit 52e4ae6 and Snow! Real Magic 6.5.4 outside dev environment)

### CODE REVIEW

File: src/main/java/org/infernalstudios/infernalexp/blocks/GlowdustBlock.java [hunk 1]
```diff
@@ -16,17 +16,73 @@
...
+        this.registerDefaultState(this.getStateDefinition().any().setValue(LAYERS, 1));
+    }
+
+    @Override
+    public boolean isPathfindable(BlockState state, BlockGetter level, BlockPos pos, PathComputationType type) {
+        switch (type) {
+            case LAND:
+                return state.getValue(LAYERS) < HEIGHT_IMPASSABLE;
+            default:
+                return false;
```
Comment (Jonathing) [inline src/main/java/org/infernalstudios/infernalexp/blocks/GlowdustBlock.java]: Use an if-statement here instead.

File: src/main/java/org/infernalstudios/infernalexp/blocks/GlowdustBlock.java [hunk 2]
```diff
@@ -36,12 +92,58 @@ public BlockState getStateForPlacement(BlockPlaceContext context) {
...
+        return state.getValue(LAYERS) == 8 ? 0.2F : 1.0F;
+    }
+
+    @Override
+    public boolean canSurvive(BlockState state, LevelReader level, BlockPos pos) {
+        BlockState blockstate = level.getBlockState(pos.below());
+        if (blockstate.is(BlockTags.SNOW_LAYER_CANNOT_SURVIVE_ON)) {
+            return false;
+        } else if (blockstate.is(BlockTags.SNOW_LAYER_CAN_SURVIVE_ON)) {
+            return true;
```
Comment (Jonathing) [inline src/main/java/org/infernalstudios/infernalexp/blocks/GlowdustBlock.java]: It might be worth making a new block tag since the snow layer tags might now account for Nether blocks. This would be a simple as

```json
{
  "values": [
    "#snow_layer_can_survive_on",
    // [Whatever else should go here]
  ]
}
```

**Review by Jonathing — CHANGES_REQUESTED** [review]

File: src/main/java/org/infernalstudios/infernalexp/blocks/GlowdustBlock.java (hunk 2 above)
Comment (SwanX1) [reply src/main/java/org/infernalstudios/infernalexp/blocks/GlowdustBlock.java]: Since this is copied from SnowLayerBlock, I didn't pay much attention to it.
I'd like to discard `snow_layer_cannot_survive_on`, and keep `snow_layer_can_survive_on`, since, despite the name, it's just a tag, which contains non-full blocks, that a layer could be placed on.
<details>
<summary>See <code>data/minecraft/tags/blocks/snow_layer_can_survive_on.json</code>:</summary>

```json
{
  "values": [
    "minecraft:honey_block",
    "minecraft:soul_sand",
    "minecraft:mud"
  ]
}
```
</details>

Comment (Jonathing) [reply src/main/java/org/infernalstudios/infernalexp/blocks/GlowdustBlock.java]: Sure

**Review by Jonathing — APPROVED** [review]
